@startuml
'https://plantuml.com/class-diagram




javafx.InventoryApp <|- javafx.InventoryManagerController
javafx.InventoryManagerController <|- ItemInfo





class javafx.InventoryApp{
+main()
+start()
}

class javafx.InventoryManagerController{
-ItemTable
-valueColumn
-serialColumn
-nameColumn
-entervaluefield
-enterserialnumberfield
-enternamefield

+changeValueColumnEvent
+ChangeSerialColumnEvent
+changeNameColumnEvent

+addnewitem
+removeitem
+sortbyvalue
+sortbyserialnumber
+sortbyname
+searchSerialNumber
+searchName
+loadaninventory
+saveinventorytofile

+initialize

}

class ItemInfo{
-name
-serialnumber
-value

+ItemInfo()
+getName()
+nameProperty()
+setName()
+getSerialNumber()
+serialnumberProperty()
+setSerialnumber()
+getValue()
+valueProperty()
+setValue()
}

@enduml